apiVersion: v1
kind: Service
metadata:
  name: {{ include "petio.fullname" . }}
  labels: {{- include "petio.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 7777
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "petio.selectorLabels" . | nindent 4 }}
