name: Lint and Test Charts

on:
  pull_request:
    paths:
    - 'charts/**'
    - '!charts/**/README.md'

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.5.3

    - uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Set up chart-testing
      uses: helm/chart-testing-action@v2.0.1

    - name: Run chart-testing (list-changed)
      id: list-changed
      run: |
        changed=$(ct list-changed)
        if [[ -n "$changed" ]]; then
          echo "::set-output name=changed::true"
        fi
    - name: Run chart-testing (lint)
      run: ct lint --config .github/ct.yaml --excluded-charts ""

    - name: Create kind cluster
      uses: helm/kind-action@v1.1.0
      if: steps.list-changed.outputs.changed == 'true'

    - name: Run chart-testing (install)
      run: ct install --config .github/ct.yaml --excluded-charts ""
