name: Release Charts

on:
  push:
    branches:
    - main
    paths:
    - 'charts/**'
    - '!charts/**/README.md'

jobs:
  pre-release:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Block concurrent jobs
      uses: softprops/turnstyle@v1
      with:
        continue-after-seconds: 180
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    needs: pre-release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
    
    - name: Install Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.5.3

    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.2.0
      with:
        charts_repo_url: https://charts.petio.tv
      env:
        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
